[pytest]
asyncio_mode = auto
pythonpath = app
testpaths = tests
filterwarnings =
    ignore:Support for class-based `config` is deprecated
    ignore:Valid config keys have changed in V2
    ignore::pytest.PytestUnhandledThreadExceptionWarning
    ignore::DeprecationWarning:fastapi_users_db_sqlmodel.*
    ignore:.*The HMAC key is.*
